export const MIN_DELAY = 3600; //one hour
export const VOTING_PERIOD = 5; //in blocks
export const VOTING_DELAY = 1; //in blocks
export const QUORUM_PERCANTAGE = 4;
export const ADDRESS_ZERO = "0x0000000000000000000000000000000000000000";
export const contractNameWhereActionTakesPlace = "NftCollection";//"NftCollection";
export const argsForFuncExecution = ["0xaf6344bc7bc538dcf7179c36fc57ccae302c1bbb", "OCAA"];//[77];
export const FUNC = "addCollection";//addCollection";//;"store";
export const PROPOSAL_DESCRIPTION = "Proposal #1 add ocaa to nft collection";//"Proposal #1: Store 77 in the Box!";
export const developmentChains = ["hardhat", "localhost"];
export const proposalsFile = "proposals.json";
export const governorContractName = "GovernorERC20";//"GovernorERC20";"GovernorERC721";
export const governanceTokenContractName = "GovernanceTokenERC20";//"GovernanceTokenERC20"; //"GovernanceTokenERC721";